### ISSUE TITLE
error run on android

### ISSUE THREAD

**Issue by white-ubuntu** [meteor/todos#110]
steps
1:git clone git@github.com:meteor/todos.git
2:cd todos
3:npm install
4:meteor update
5:meteor run android

error:
ijoy@ijoy:~/meteorPro/todos$ meteor run android
[[[[[ ~/meteorPro/todos ]]]]]                 

=> Started proxy.                             
=> Started MongoDB.                           
shell.js: internal errorject                 -
Error: ENOENT, no such file or directory '/home/ijoy/meteorPro/todos/.meteor/local/cordova-build/www/*'
    at Object.fs.statSync (fs.js:696:18)
    at /home/ijoy/meteorPro/todos/node_modules/shelljs/src/cp.js:148:21
    at Array.forEach (native)
    at Object._cp (/home/ijoy/meteorPro/todos/node_modules/shelljs/src/cp.js:144:13)
    at Object.cp (/home/ijoy/meteorPro/todos/node_modules/shelljs/src/common.js:240:23)
    at updateWwwFrom (/home/ijoy/meteorPro/todos/.meteor/local/cordova-build/platforms/android/cordova/lib/prepare.js:99:11)
    at Api.module.exports.prepare (/home/ijoy/meteorPro/todos/.meteor/local/cordova-build/platforms/android/cordova/lib/prepare.js:38:19)
    at Api.prepare (/home/ijoy/meteorPro/todos/.meteor/local/cordova-build/platforms/android/cordova/Api.js:159:45)
    at /home/ijoy/.meteor/packages/meteor-tool/.1.3.1.du5uow++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/prepare.js:101:32
    at _fulfilled (/home/ijoy/.meteor/packages/meteor-tool/.1.3.1.du5uow++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/ijoy/.meteor/packages/meteor-tool/.1.3.1.du5uow++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/ijoy/.meteor/packages/meteor-tool/.1.3.1.du5uow++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
    at /home/ijoy/.meteor/packages/meteor-tool/.1.3.1.du5uow++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/q/q.js:810:14
    at flush (/home/ijoy/.meteor/packages/meteor-tool/.1.3.1.du5uow++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:458:13)

set:
   jdk1.7
   sdk22
   ubuntu14.04

**Comment by tmeasday** [comment]
Is this the same as https://github.com/meteor/todos/issues/107#issuecomment-206680412 ?

**Comment by white-ubuntu** [comment]
after i clone a new todos project,i modify imports/ui/layouts/app-body.html
`<body>
<template name="App_body">
   ......
</template>
</body>`

then run  
npm install
meteor update
meteor run android

the error is:
FAILURE: Build failed with an exception.
   
   * What went wrong:
   A problem occurred configuring root project 'android'.
   > Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches com.android.support:support-v4:[13.0.0,).
   Searched in the following locations:
   https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
   https://repo1.maven.org/maven2/com/android/support/support-v4/
   https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/maven-metadata.xml
   https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/
   Required by:
   :android:unspecified > org.xwalk:xwalk_core_library:17.46.448.10
   
   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
   Error code 1 for command: /home/ijoy/meteorPro/todos/.meteor/local/cordova-build/platforms/android/gradlew with args:
   cdvBuildDebug,-b,/home/ijoy/meteorPro/todos/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=x86,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true undefined
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)
                                              
/home/ijoy/.meteor/packages/coffeescript/.1.0.16.869ukb++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
ExitWithCode:1


i shut down emulator,
then retry run
meteor run android

the error is:
shell.js: internal errorugins                -
Error: ENOENT, no such file or directory '/home/ijoy/meteorPro/todos/.meteor/local/cordova-build/www/*'
    at Object.fs.statSync (fs.js:696:18)
    at /home/ijoy/meteorPro/todos/node_modules/shelljs/src/cp.js:148:21
    at Array.forEach (native)
    at Object._cp (/home/ijoy/meteorPro/todos/node_modules/shelljs/src/cp.js:144:13)
    at Object.cp (/home/ijoy/meteorPro/todos/node_modules/shelljs/src/common.js:240:23)
    at updateWwwFrom (/home/ijoy/meteorPro/todos/.meteor/local/cordova-build/platforms/android/cordova/lib/prepare.js:99:11)
    at Api.module.exports.prepare (/home/ijoy/meteorPro/todos/.meteor/local/cordova-build/platforms/android/cordova/lib/prepare.js:38:19)
    at Api.prepare (/home/ijoy/meteorPro/todos/.meteor/local/cordova-build/platforms/android/cordova/Api.js:159:45)
    at /home/ijoy/.meteor/packages/meteor-tool/.1.3.1.du5uow++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/prepare.js:101:32
    at _fulfilled (/home/ijoy/.meteor/packages/meteor-tool/.1.3.1.du5uow++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/ijoy/.meteor/packages/meteor-tool/.1.3.1.du5uow++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/ijoy/.meteor/packages/meteor-tool/.1.3.1.du5uow++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
    at /home/ijoy/.meteor/packages/meteor-tool/.1.3.1.du5uow++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/q/q.js:810:14
    at flush (/home/ijoy/.meteor/packages/meteor-tool/.1.3.1.du5uow++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:458:13)

**Comment by electr0sheep** [comment]
I think this issue is the same as what I was experiencing, and a duplicate of my issue.

Try this
```bash
git clone http://github.com/meteor/todos
cd todos
meteor npm install
meteor run android
```

That resolved the issue for me.

**Comment by white-ubuntu** [comment]
thank for your answer,
