### ISSUE TITLE
Meteor  run error on windows 7.

### ISSUE THREAD

**Issue by thearabbit** [meteor/todos#82]
I base on win 7.
Meteor run error
```js
Error: sourcePath not a file: D:\meteor_app\todos\i18n\en.i18n.json  
    at ImportScanner._ensureSourcePath (C:\tools\isobuild\import-scan
ner.js:208:13)                                                       
    at C:\tools\isobuild\import-scanner.js:101:28                    
    at Array.forEach (native)                                        
    at ImportScanner.addInputFiles (C:\tools\isobuild\import-scanner.
js:100:11)                                                           
```

**Comment by tmeasday** [comment]
Any thoughts @stubailo?

**Comment by thearabbit** [comment]
Excuse me, I don't understand about you.

**Comment by tmeasday** [comment]
I was just asking @stubailo who knows a thing or two about our windows support if he has an idea of what this might be.

**Comment by jakobrosenberg** [comment]
Same error on Windows 10.

**Comment by stubailo** [comment]
What path is your Meteor app root in?

**Comment by jakobrosenberg** [comment]
In my case "C:\Users\jakob\kitchensink\todos"

```
Error: sourcePath not a file: C:\Users\jakob\kitchensink\todos\i18n\en.i18n.json
    at ImportScanner._ensureSourcePath (C:\tools\isobuild\import-scanner.js:208:13)
    at C:\tools\isobuild\import-scanner.js:101:28
```` 

The source path exists and it is a file. C:\tools doesn't however exist.

**Comment by jebarjonet** [comment]
I have the same error with the [todos app](https://github.com/meteor/todos) and **1.3-beta.12** release when I call `meteor` command.
```
Error: sourcePath not a file: C:\Dev\todos\i18n\en.i18n.json
    at ImportScanner._ensureSourcePath (C:\tools\isobuild\import-scanner.js:208:13)
    at C:\tools\isobuild\import-scanner.js:101:28
    at Array.forEach (native)
    at ImportScanner.addInputFiles (C:\tools\isobuild\import-scanner.js:100:11)
    at C:\tools\isobuild\compiler-plugin.js:709:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:689:19)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:749:8)
    at C:\tools\isobuild\bundler.js:516:12
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:507:18)
    at C:\tools\isobuild\bundler.js:2232:14
    at C:\tools\isobuild\bundler.js:2322:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Me\AppData\Local\.meteor\packages\meteor-tool\1.1.13-beta.12\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2321:7
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2213:31)
    at C:\tools\runners\run-app.js:586:36
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at bundleApp (C:\tools\runners\run-app.js:576:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:629:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:881:28)
    at C:\tools\runners\run-app.js:406:12
```
Windows 10, everything fine with 1.2 release.

**Comment by Nolapete** [comment]
Was able to get todos app to work on windows 10 (will test tonight on windows 7 to confirm works there as well)

clone repo then
```
meteor create newapp
cd newapp
rm -rf client
rm -rf server
del package.json
```
replace newapp/.meteor/packages with todos/.meteor/packages

copy everything from todos except .git and .meteor

in newapp folder:
```
npm install
meteor
```

**Comment by hwillson** [comment]
Both the Blaze and React todos versions have now been fully updated to the latest version of Meteor, and had their packages and npm dependencies updated as well. Everything should now work properly on Windows (7, 8, 10, etc.). Closing this off - if anyone notices any issues, please post back. Thanks!
